export const users = [
  [
    {
      _id: '66102ce0407b358473615d5c',
      index: 0,
      guid: '6b6b3a51-d650-4e0b-bbbd-94dfd9a37aa2',
      isActive: false,
      balance: '$1,472.86',
      picture: 'http://placehold.it/32x32',
      age: 23,
      eyeColor: 'brown',
      name: 'Mara Talley',
      gender: 'female',
      company: 'EVENTAGE',
      email: 'maratalley@eventage.com',
      phone: '+1 (889) 468-2681',
      address: '623 Herzl Street, Ernstville, Palau, 2530',
      about:
        'Nulla esse cillum qui tempor. Nostrud ullamco dolore officia qui fugiat velit pariatur consectetur quis cupidatat aliquip eiusmod deserunt. Est voluptate laboris mollit aliqua exercitation ex esse. Aliquip deserunt velit quis veniam velit exercitation ipsum deserunt aliquip.\r\n',
      registered: '2018-06-25T07:50:03 -03:00',
      latitude: -41.139784,
      longitude: -17.26058,
      tags: ['minim', 'enim', 'nulla', 'ex', 'commodo', 'enim', 'aute'],
      friends: [
        {
          id: 0,
          name: 'Frazier Guzman',
        },
        {
          id: 1,
          name: 'Roxanne Mathis',
        },
        {
          id: 2,
          name: 'Lynnette Molina',
        },
      ],
      greeting: 'Hello, Mara Talley! You have 8 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '66102ce029481422a9d07a49',
      index: 1,
      guid: '8f0994f2-b5c1-41ca-a0d3-33d3f8bcc78c',
      isActive: false,
      balance: '$3,816.79',
      picture: 'http://placehold.it/32x32',
      age: 20,
      eyeColor: 'blue',
      name: 'Deanna Farrell',
      gender: 'female',
      company: 'WAAB',
      email: 'deannafarrell@waab.com',
      phone: '+1 (816) 436-3168',
      address: '904 Alabama Avenue, Talpa, West Virginia, 9951',
      about:
        'Reprehenderit nostrud sint sit veniam. Occaecat pariatur duis duis irure consequat duis aliquip voluptate adipisicing culpa amet elit. Eu excepteur velit aliquip cupidatat esse duis officia. Exercitation ut sunt pariatur ut.\r\n',
      registered: '2020-05-13T09:31:56 -03:00',
      latitude: -25.293893,
      longitude: -147.435373,
      tags: ['nisi', 'ad', 'incididunt', 'eiusmod', 'sint', 'veniam', 'est'],
      friends: [
        {
          id: 0,
          name: 'Gracie Craig',
        },
        {
          id: 1,
          name: 'Carney Montgomery',
        },
        {
          id: 2,
          name: 'Goodman Harrington',
        },
      ],
      greeting: 'Hello, Deanna Farrell! You have 1 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '66102ce0bd4ad03099eb9f99',
      index: 2,
      guid: 'e75db4c7-619d-4260-ad81-367bef2f8f1f',
      isActive: true,
      balance: '$1,135.52',
      picture: 'http://placehold.it/32x32',
      age: 31,
      eyeColor: 'blue',
      name: 'Cassandra Lindsay',
      gender: 'female',
      company: 'PEARLESSA',
      email: 'cassandralindsay@pearlessa.com',
      phone: '+1 (809) 586-3913',
      address: '384 Eagle Street, Edinburg, Mississippi, 6103',
      about:
        'Enim id est esse fugiat magna id laborum in sint. Nostrud ut aliquip nulla exercitation ut dolor aute. Aliqua fugiat est dolore quis ullamco veniam veniam veniam officia in esse. Ullamco ea cillum eu pariatur et aliquip incididunt fugiat dolor nostrud adipisicing esse exercitation excepteur. Pariatur culpa eiusmod occaecat commodo. Duis cupidatat ad consequat incididunt occaecat laboris labore aliquip Lorem esse laborum commodo excepteur enim. Ex amet velit nulla anim commodo.\r\n',
      registered: '2022-05-06T07:01:59 -03:00',
      latitude: 40.279122,
      longitude: -169.717338,
      tags: [
        'laboris',
        'anim',
        'ea',
        'consectetur',
        'duis',
        'labore',
        'tempor',
      ],
      friends: [
        {
          id: 0,
          name: 'Mcdaniel Holcomb',
        },
        {
          id: 1,
          name: 'Josie Love',
        },
        {
          id: 2,
          name: 'Charlotte Green',
        },
      ],
      greeting: 'Hello, Cassandra Lindsay! You have 7 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '66102ce0106be220aae68ba8',
      index: 3,
      guid: 'f8634e29-4978-42af-b3db-4369dc558bbe',
      isActive: false,
      balance: '$1,977.54',
      picture: 'http://placehold.it/32x32',
      age: 29,
      eyeColor: 'brown',
      name: 'Perry Hayden',
      gender: 'male',
      company: 'OBONES',
      email: 'perryhayden@obones.com',
      phone: '+1 (818) 402-3972',
      address: '817 Arion Place, Fulford, Utah, 7200',
      about:
        'Consectetur eu excepteur sint elit quis ipsum. Est minim ut adipisicing nisi adipisicing anim laborum aliqua laboris officia laboris. Ullamco proident velit proident proident cupidatat occaecat occaecat laborum excepteur reprehenderit aliqua anim. Lorem ea consequat dolore ut. Nostrud quis in ad exercitation.\r\n',
      registered: '2022-10-23T08:50:56 -03:00',
      latitude: 73.997518,
      longitude: 132.921178,
      tags: ['aliquip', 'nulla', 'ad', 'excepteur', 'ea', 'magna', 'ea'],
      friends: [
        {
          id: 0,
          name: 'Felicia Zimmerman',
        },
        {
          id: 1,
          name: 'Hopkins Emerson',
        },
        {
          id: 2,
          name: 'Aline Doyle',
        },
      ],
      greeting: 'Hello, Perry Hayden! You have 2 unread messages.',
      favoriteFruit: 'strawberry',
    },
    {
      _id: '66102ce071307cc9b18e7e8b',
      index: 4,
      guid: '476b7951-9649-49ae-a744-681a3473abe0',
      isActive: true,
      balance: '$2,993.31',
      picture: 'http://placehold.it/32x32',
      age: 32,
      eyeColor: 'green',
      name: 'Ashlee Luna',
      gender: 'female',
      company: 'SPACEWAX',
      email: 'ashleeluna@spacewax.com',
      phone: '+1 (857) 569-3443',
      address: '116 Campus Place, Matheny, Tennessee, 6797',
      about:
        'Nostrud sit deserunt dolore nulla excepteur dolor ea amet enim et commodo et ad. Consequat nulla Lorem do mollit. Amet laboris minim anim quis consequat ad aliqua veniam adipisicing ad. Aliqua tempor est eiusmod est sunt dolor quis officia Lorem. Magna elit aute sunt eu deserunt nulla elit cupidatat aute sit pariatur incididunt.\r\n',
      registered: '2015-03-02T12:05:51 -03:00',
      latitude: -19.785799,
      longitude: 66.232788,
      tags: [
        'ex',
        'ullamco',
        'reprehenderit',
        'dolor',
        'deserunt',
        'occaecat',
        'sint',
      ],
      friends: [
        {
          id: 0,
          name: 'Lizzie Garrison',
        },
        {
          id: 1,
          name: 'Miller Riddle',
        },
        {
          id: 2,
          name: 'Madge Davenport',
        },
      ],
      greeting: 'Hello, Ashlee Luna! You have 5 unread messages.',
      favoriteFruit: 'strawberry',
    },
    {
      _id: '66102ce0e22689def8b99dc5',
      index: 5,
      guid: 'eb1493e2-3f92-42ff-9c6b-dd0ffdcd7085',
      isActive: false,
      balance: '$3,401.96',
      picture: 'http://placehold.it/32x32',
      age: 32,
      eyeColor: 'green',
      name: 'Franco Serrano',
      gender: 'male',
      company: 'CEPRENE',
      email: 'francoserrano@ceprene.com',
      phone: '+1 (935) 490-2522',
      address: '568 Degraw Street, Boyd, California, 8907',
      about:
        'Amet fugiat qui eu cillum id elit. Qui quis cupidatat nulla ex id ipsum mollit. Commodo dolor labore ullamco officia dolore incididunt excepteur. Reprehenderit sunt minim deserunt veniam cillum mollit excepteur nisi. Eiusmod consectetur non cillum ullamco. Non cupidatat consectetur consectetur officia voluptate Lorem cupidatat aliquip Lorem aliqua ea commodo.\r\n',
      registered: '2014-02-19T12:09:39 -04:00',
      latitude: -80.335098,
      longitude: 24.714415,
      tags: [
        'est',
        'consectetur',
        'magna',
        'elit',
        'tempor',
        'aute',
        'adipisicing',
      ],
      friends: [
        {
          id: 0,
          name: 'Butler Bray',
        },
        {
          id: 1,
          name: 'Heath Abbott',
        },
        {
          id: 2,
          name: 'Kinney Valenzuela',
        },
      ],
      greeting: 'Hello, Franco Serrano! You have 9 unread messages.',
      favoriteFruit: 'apple',
    },
    {
      _id: '66102ce0bdf82b5b50494f37',
      index: 6,
      guid: '9eb69206-a49f-4db4-8c0f-ca2c1c425689',
      isActive: true,
      balance: '$2,651.44',
      picture: 'http://placehold.it/32x32',
      age: 28,
      eyeColor: 'brown',
      name: 'Morales Rose',
      gender: 'male',
      company: 'STREZZO',
      email: 'moralesrose@strezzo.com',
      phone: '+1 (804) 425-2079',
      address: '717 Delmonico Place, Belgreen, Oklahoma, 7597',
      about:
        'Sint aute consequat exercitation nulla irure ad excepteur sunt fugiat sunt commodo mollit. Incididunt laborum consectetur in laboris sunt sit nisi magna nisi deserunt enim irure ex ex. Anim est esse pariatur laboris commodo voluptate adipisicing mollit eu velit. Id ea eu quis velit ea ullamco nulla est ipsum voluptate cupidatat ad.\r\n',
      registered: '2020-11-18T06:50:58 -03:00',
      latitude: 39.694699,
      longitude: -4.98859,
      tags: ['non', 'et', 'proident', 'tempor', 'elit', 'aliqua', 'ullamco'],
      friends: [
        {
          id: 0,
          name: 'Nettie Lowery',
        },
        {
          id: 1,
          name: 'Jimmie Cruz',
        },
        {
          id: 2,
          name: 'Kent Berg',
        },
      ],
      greeting: 'Hello, Morales Rose! You have 1 unread messages.',
      favoriteFruit: 'strawberry',
    },
  ],
];
